//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioMit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Blazor_Variable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Blazor_Variable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiblioMit.Resources.Blazor.Variable", typeof(Blazor_Variable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acidification.
        /// </summary>
        public static string Acidification {
            get {
                return ResourceManager.GetString("Acidification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceanographic.
        /// </summary>
        public static string Oceanographic {
            get {
                return ResourceManager.GetString("Oceanographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceanographic Variables.
        /// </summary>
        public static string Oceanographic_Variables {
            get {
                return ResourceManager.GetString("Oceanographic Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen.
        /// </summary>
        public static string Oxigen {
            get {
                return ResourceManager.GetString("Oxigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytoplankton.
        /// </summary>
        public static string Phytoplankton {
            get {
                return ResourceManager.GetString("Phytoplankton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        public static string Salinity {
            get {
                return ResourceManager.GetString("Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Temperature.
        /// </summary>
        public static string Surface_Temperature {
            get {
                return ResourceManager.GetString("Surface Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Phytoplankton.
        /// </summary>
        public static string Total_Phytoplankton {
            get {
                return ResourceManager.GetString("Total Phytoplankton", resourceCulture);
            }
        }
    }
}
