//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioMit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models_Entities_Semaforo_LarvaType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models_Entities_Semaforo_LarvaType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiblioMit.Resources.Models.Entities.Semaforo.LarvaType", typeof(Models_Entities_Semaforo_LarvaType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-Larva.
        /// </summary>
        public static string D_Larva {
            get {
                return ResourceManager.GetString("D-Larva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyed Larva.
        /// </summary>
        public static string Eyed_Larva {
            get {
                return ResourceManager.GetString("Eyed Larva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larva Type (count).
        /// </summary>
        public static string Larva_Type__count_ {
            get {
                return ResourceManager.GetString("Larva Type (count)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbanate Larva.
        /// </summary>
        public static string Umbanate_Larva {
            get {
                return ResourceManager.GetString("Umbanate Larva", resourceCulture);
            }
        }
    }
}
